### ISSUE TITLE
malformed page title

### ISSUE THREAD

**Issue by propertunist** [AU-Landing-Project/liked_content#2]
i don't know why this is occuring.. however, i noticed today after styling the page titles across the whole site that the liked content page has a superfluous title element.. so my theme has an extra element which looks weird. the h2 element appears twice.

<div class="elgg-head clearfix">
    <h2 class="elgg-heading-main"></h2><h2>resonant items</h2>
</div>

**Comment by beck24** [comment]
Fixed in 1.9+ version
